export const reserva_template = {
  document: [
    {
      type: "title",
      id: "0",
      text: "RESERVA DE COMPRA",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "1",
      text: "En la {ciudad}, el día {fecha}, se suscribe esta reserva de compra respecto de {tipoInmueble}, con frente a {direccionInmueble}, {localidadInmueble}, en adelante el “Inmueble”. ",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "2",
      text: "Suscribe {nombreReservante}, DNI N° {dniReservante}, CUIT N° {cuitReservante}, con dirección en {direccionReservante}, y constituyendo domicilio electrónico en los términos del art 75 del CC y CN en {emailReservante}  (en adelante, el “Reservante”), manifiesta su interés en la COMPRA del inmueble citado y ENTREGA en calidad de RESERVA “AD REFERENDUM” a la firma Fabián Achával Propiedades, sita en Av. Alvear 1890 piso 12, de la Ciudad Autónoma de Buenos Aires, email: ventas@fabianachaval.com, cuyo titular resulta ser Fabián Achával, DNI 28.641.336, Matrícula CUCICBA Nº 6576 y Matrícula CMCPSI N° 6375, y quien actúa en carácter de corredor inmobiliario, y quien recibe de conformidad la suma de  Dólares Estadounidenses {montoReserva} en efectivo, sirviendo el presente de suficiente y formal recibo. Durante la vigencia del plazo establecido, el OFERENTE mantiene la oferta con carácter irrevocable, lo que expresamente es aceptado por el OFERENTE como condición de la presente. Dicha reserva se toma con prioridad exclusiva de compra por el precio ofertado hasta {diasValidezReserva} dias de recibida la reserva.\n",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "3",
      text: "La presente Oferta de Compra anula y reemplaza a cualquier oferta de compra anterior que hubiere efectuado el Oferente en relación al mismo Inmueble, dejándose constancia de que los importes que eventualmente hubiere entregado con anterioridad se encuentran comprendidos en la suma indicada en el encabezamiento.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "4",
      text: "La oferta se efectúa en las siguientes condiciones:",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "5",
      text: "[PRIMERA:] PRECIO TOTAL Y FORMA DE PAGO:  Dólares Estadounidenses {valorInmueble} pagaderos en su totalidad al momento de otorgarse la escritura traslativa de dominio y simultánea entrega de posesión del inmueble objeto de esta venta, que tendrá lugar dentro de los 10 días corridos de la notificación de la aceptación. La escritura se realizará por ante el Escribano que designará la parte compradora. Se acuerda como condición del presente contrato que la compradora realizará los pagos con Dólares de los Estados Unidos de América billete emitidos por la casa de la moneda de los Estados Unidos de América con posterioridad al año 1996 y conocidos habitualmente como billetes de “Cara grande”, en excelente estado de conservación. Los billetes serán de denominación de cien (100).\n",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "6",
      text: "[PRIMERA BIS:] REFUERZO: Una vez aceptada la oferta realizada por parte del Propietario, el OFERENTE se compromete a realizar un Refuerzo de Reserva (en adelante, el “Refuerzo”) de  Dólares Estadounidenses diez mil (USD10.000), en un plazo máximo de 7 días hábiles desde la notificación de la aceptación, bajo apercibimiento de tener por perdida la suma entregada a favor de la firma Fabián Achával Propiedades.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "7",
      text: "[SEGUNDA:] Los gastos, honorarios notariales, sellos e impuestos que correspondan; serán soportados por las Partes de acuerdo a derecho y prácticas notariales.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "8",
      text: "[TERCERA:] El lugar donde deberán realizarse todos los pagos lo determinará la parte vendedora en una institución financiera o escribanía, siempre dentro del ámbito de Ciudad Autónoma de Buenos Aires.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "9",
      text: "[CUARTA:] Esta compraventa está sujeta a títulos perfectos, con todos los impuestos, tasas, servicios y expensas completamente cancelados a la fecha de la escrituración y entrega de la posesión. El Inmueble se entregará libre de ocupantes. ",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "10",
      text: "[QUINTA:] CASO FORTUITO Y FUERZA MAYOR. Las Partes renuncian expresamente a cualquier caso fortuito o de fuerza mayor que pudiese afectar esta venta, asumiendo la responsabilidad de ello, y renunciando expresamente a la teoría de la imprevisión o cualquier otro instituto similar atento la renuncia expresa efectuada y el momento en el que se realiza esta venta. Para el supuesto de imposibilidad de traslado por disposición legal actual o futura de cuarentena, por esta única excepción, podrá prorrogarse el pago del saldo de precio, la posesión y Escritura traslativa de dominio por el plazo de 5 (cinco) días hábiles posteriores al cese de dicho confinamiento forzoso sin que implique multas ni incumplimiento a ninguna de las partes por esta excepción. ",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "11",
      text: "[SEXTA:] El OFERENTE acepta y reconoce irrevocablemente que es condición expresa y esencial de la presente operación: a) que el pago del precio se efectúe en DÓLARES ESTADOUNIDENSES BILLETES en moneda de libre disponibilidad. A este efecto el interesado declara bajo juramento que en la fecha de suscripción de la presente, posee la totalidad de los billetes dólares estadounidenses necesarios y la libre disponibilidad de los mismos, o el medio para conseguirlos, para cancelar las obligaciones asumidas en la presente y se obliga a mantenerlos bajo su resguardo hasta el momento de otorgarse la escritura traslativa de dominio para poder realizar el pago del precio; b) el OFERENTE manifiesta tener conocimiento y haber recibido asesoramiento profesional sobre la modificación y unificación del Código Civil y Comercial de la Nación y el decreto 70/23  respecto de las obligaciones contraídas en monedas que no sean de curso legal en la República Argentina, y teniendo en cuenta que las partes declaran que constituye una condición expresa y esencial para la celebración de la operación de compraventa que el pago del precio se realice en dólares estadounidenses y exclusivamente en billetes de la moneda norteamericana, el OFERENTE acepta expresamente como condición contractual lo dispuesto por el decreto 70/23 del P.E.N. respecto a la modificación de los arts. 765 y 766 del Código Civil y Comercial de la Nación. c) el OFERENTE renuncia en forma expresa e irrevocable a invocar la teoría de la imprevisión, la teoría del abuso del derecho y/o cualquier otro instituto previsto o no, sea por la ley o por la jurisprudencia y que esté vigente en la actualidad o se establezca en el futuro para pretender la revisión de lo pactado, una disminución o reajuste del precio fijado en forma definitiva en la compraventa.-",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "12",
      text: "[SÉPTIMA:] La presente reserva se efectúa “Ad-Referendum” del propietario: ",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "13",
      text: "A) Si el titular de dominio del Inmueble aceptara los términos y condiciones de esta oferta dentro del plazo vigencia de la misma, deberá dar su conformidad suscribiendo al pie de la presente. El OFERENTE será notificado de esta aceptación mediante correo electrónico a la dirección denunciada por el mismo en el encabezado de la Reserva y quedará obligado a concurrir dentro del plazo estipulado en la PRIMERA BIS de la reserva a las oficinas de Fabián Achával Propiedades en días hábiles de lunes a viernes en el horario de 10 a 18 hs, a fin de notificarse en forma personal y a efectuar el Refuerzo especificado en la PRIMERA BIS de la presente. Si no se presentare a efectuar el Refuerzo de Reserva comprometido, se entenderá por desistida la oferta realizada, con pérdida de la suma entregada en concepto de indemnización a favor de los propietarios del inmueble objeto de la presente. Dicho desistimiento tendrá carácter irrevocable y la pérdida de la suma entregada se efectuará como única indemnización cuya mora operará en forma automática por el mero vencimiento de plazos, sin necesidad de interpelación alguna judicial o extrajudicial y como expresa condición contractual. Si se presentare en el plazo acordado y efectúa el Refuerzo de la reserva, a partir de ese momento, las partes se comprometen a asistir a la firma de la escritura traslativa de dominio dentro del plazo fijado en la cláusula 1 en un horario que fijen de común acuerdo. En caso de no presentarse el/los titular/es de dominio del Inmueble a suscribir dicha Escritura traslativa de dominio el día o lugar indicado, la firma Fabián Achával Propiedades, reintegrará al OFERENTE el importe entregado en este acto en concepto de reserva, y el entregado en concepto de Refuerzo de Reserva; y por su parte el/los titular/es de dominio del Inmueble, deberá/n entregar al Reservante otra suma igual en concepto de única indemnización. Si fuere el Reservante quien no se presentara a dicha firma en las condiciones acordadas, habiendo vencido el plazo acordado, autoriza en forma expresa a la firma Fabián Achával Propiedades a entregar al/los titular/es de dominio del Inmueble, la suma entregada en este acto como reserva, y la que sea entregada en concepto de Refuerzo, en concepto de única indemnización por su incumplimiento; o",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "14",
      text: "B) si por el contrario, el/los titular/es de dominio del Inmueble rechazara/n la presente oferta, o si hubiera vencido el plazo para su aceptación, sin manifestación alguna de su parte al respecto, la presente reserva caducará de pleno derecho, sin necesidad de notificación alguna. En tal caso, se devolverá al OFERENTE las sumas entregadas hasta el momento en igual especie y cantidad en este acto y en ocasión del Refuerzo, dentro de las 48 horas hábiles de su rechazo o del vencimiento del plazo de vigencia de la presente, según corresponda, que deberán ser retiradas en las oficinas de la Inmobiliaria días hábiles de lunes a viernes de 10 a 18 hs.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "15",
      text: "[OCTAVA:] MORA AUTOMÁTICA y NOTIFICACIONES: Se pacta expresamente la MORA AUTOMÁTICA por el mero vencimiento de plazos sin necesidad de notificación alguna judicial o extrajudicial. Todas las notificaciones electrónicas comunicadas vía mail serán válidas a todos los efectos del presente si se dirigen a los mails denunciados en el presente.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "16",
      text: "[NOVENA:] En el acto de firmarse la escritura traslativa de dominio la parte compradora se compromete a abonar a Fabián Achával Propiedades el 4% más IVA sobre el monto total de la compraventa en concepto de honorarios por intermediación. Se fija expresamente que los honorarios se pagarán en dólares estadounidenses y en efectivo el día de la operación.\nDe conformidad se firman 3 ejemplares de un mismo tenor y a un solo efecto en el lugar y fecha indicados en el encabezado.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "17",
      text: "{nombreReservante}, DNI {dniReservante}, Firma: ____________________",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "18",
      text: "FABIÁN ACHAVAL PROPIEDADES, Firma: ___________________",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "19",
      text: "_________________________________________________________________________",
      dependencies: [],
    },
    {
      type: "title",
      id: "20",
      text: "CONFORMIDAD Y ACEPTACIÓN DE LA PARTE VENDEDORA",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "21",
      text: "Leídos los términos de la reserva que antecede y en mi carácter de titular de dominio del Inmueble objeto de la misma, ACEPTO en forma irrevocable, la totalidad de los términos y condiciones expresados en la misma, retirando el Inmueble de la venta a partir del día de la fecha y comprometiéndome a abonar a Fabián Achával Propiedades, _____ más IVA sobre el monto total de la compraventa en concepto de honorarios por intermediación.\nEn la Ciudad Autónoma de Buenos Aires, el _________________________________.",
      dependencies: [],
    },
    {
      type: "newParagraph",
      id: "22",
      text: "{nombreVendedor}, DNI {dniVendedor}, Firma: ___________________",
      dependencies: [],
    },
  ],
};
